@baseUrl = http://localhost:9000
@authToken = {{loginADIMIN.response.body.token}}



# ==========================
# 🚀 ADMIN
# ==========================

# @name Cadastrouser
POST {{baseUrl}}/user
Content-Type: application/json

{
    "nome": "Ingred",
    "senha": "1234",
    "Role": "admin"
 
}

###
# @name loginADIMIN
POST {{baseUrl}}/login
Content-Type: application/json

{
  "nome": "Ingred",
   "senha": "1234"


}



###
GET {{baseUrl}}/check
Content-Type: application/json
Authorization: Bearer {{authToken}}

# ==========================
# 🚀 Reservas
###
# @name mostrarSalasabertas
GET {{baseUrl}}/salas
Content-Type: application/json
Authorization: Bearer {{authToken}}
###
# @name mostrarSalasADM
GET {{baseUrl}}/reservas
Content-Type: application/json
Authorization: Bearer {{authToken}}

###
# @name CadastroReservas
POST {{baseUrl}}/reservar
Content-Type: application/json
Authorization: Bearer {{authToken}}

[{ 
    "id": 70553,
    "salaNome": "aulas de matemática",
    "disponivel": false,
    "data": "aaa/aaa/aa"
}]

# ==========================
# 🚀 FILMES
###
# @name CadastroFilmes
POST {{baseUrl}}/filmes
Content-Type: application/json

[{ 
  "titulo": "Parasggidtaf",
  "genero": "Dorama",
  "favorito": true
}]
###
# @name MostratosdosFilmes
GET {{baseUrl}}
Content-Type: application/json


###
# @name filmesFavoritos
GET {{baseUrl}}/favoritos
Content-Type: application/json

###
# @name filmesDoGeneroDrama
GET {{baseUrl}}/drama
Content-Type: application/json
###

###
# @name analiseTotais
GET {{baseUrl}}/totais
Content-Type: application/json
###
# @name AtualizarFilmepartefAVORITO
PATCH {{baseUrl}}/6
Content-Type: application/json

{
  "favorito": true
}
